### ISSUE TITLE
command is send 3x

### ISSUE THREAD

**Issue by Jovink** [athombv/am.smarter#13]
Hi,
I have made a flow that if the coffee is ready the coffee keeps hot for  5 minutes.
But that command (and the others as well) is given 3 times. 
The coffee machine doesn't like it.

**Comment by RobinBol** [comment]
Strange, when I find the time I'll take a look!

**Comment by Jovink** [comment]
You can close this issue. After a reboot everything works fine.

**Comment by RobinBol** [comment]
Oke thanks!
