### ISSUE TITLE
Coffee machine 2nd gen not found

### ISSUE THREAD

**Issue by cbho** [athombv/am.smarter#20]
When trying to add the 2nd gen coffee machine, the app says "No new devices found".
Tried both the SDK2 and the Beta-version of the app on GitHub.
Something gone wrong - or just not supported yet?

**Comment by saro1975** [comment]
Hi, here still the same problem, homey does not see the coffe machine. Please advise

**Comment by RobinBol** [comment]
It seems the smarter coffee v2 uses a different api then v1, which is why it is not supported by the smarter app. I will leave this issue open as an enhancement.

**Comment by RobinBol** [comment]
Moved this issue to our central issue tracker: https://github.com/athombv/homey/issues/1983
