### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by jklflipper** [athombv/am.smarter#7]
Are there any known problems with this app because my coffemachine doesn't work from the flow

**Comment by RobinBol** [comment]
Well, nothing really changed. Might be a network issue? Maybe the machine got a new ip?

**Comment by jklflipper** [comment]
Hallo Robin,


Hartelijk dank voor je snelle reactie. Ik ben zo vrij om in het Nederlands te antwoorden.


Ik heb de Smarter app opnieuw geïnstalleerd naar aanleiding van je mail. De koffiemachine heeft een vast ip-adres (ik hoef dit toch niet ergens op te geven in Homey? Bij het toevoegen vindt hij hem vanzelf.). Ik heb de app pas kortgeleden geïnstalleerd en er vandaag weer naar gekeken.


Als ik onderstaande flow maak en deze test krijg ik een rode driehoek:


[cid:4d8d28ac-2930-4604-af5b-f88c9b03d2e5]



Ook als ik tegen Homey "koffie" roep verstaat hij mij wel maar de koffie gaat niet pruttelen. Als ik vervolgens met de app op mijn telefoon de koffie aanzet (met de Smarter app) dan werkt hij wel. Ook krijg ik op mijn telefoon de melding van de Smarter app dat de koffie klaar is. Helaas krijg ik die melding van Homey niet


[cid:052c1a97-274c-4ad1-83e5-8be048a7da43]

Enig idee wat het probleem zou kunnen zijn?

Alvast bedankt voor de tijd en moeite.

Met vriendelijke groet,

Felix Parnemann

________________________________
Van: Robin Bolscher <notifications@github.com>
Verzonden: dinsdag 24 januari 2017 20:34
Aan: athombv/am.smarter
CC: jklflipper; Author
Onderwerp: Re: [athombv/am.smarter] Doesn't work anymore? (#7)


Well, nothing really changed. Might be a network issue? Maybe the machine got a new ip?

-

**Comment by RobinBol** [comment]
Hi, I think something went wrong with your screenshots, I can't see them, could you hover over the red triangle with your mouse, this will show the error message which I need to find the problem.

**Comment by jklflipper** [comment]
Hallo Robin,


Ik heb de screenshots als bijlage toegevoegd. Als ik over het driehoekje hover geeft hij offline aan. Echter volgens netscan en de app van Smarter zelf op de telefoon is hij nog steeds online. Ik moet dan de app uitschakelen en weer inschakelen.


Indien de app in Homey wel verbinding heeft vallen mij onderstaande zaken op:


- het liedje of de melding dat de koffie klaar is pas komt op het moment dat de warmhoud plaat uitschakeld. In mijn geval dus een kwartier.

- Ik heb met de app (Smarter-app android) op de telefoon ook gecontroleerd of hij dat dan eerder doet indien ik het warmhouden via de app stop en dat doet hij dus ook.

- Als ik in Homey instel dat hij mij een bericht moet sturen indien de warmhoudplaat stopt gebeurd dit trouwens ook niet.

- Als ik koffie zet via Homey krijg ik wel een melding dat de koffie gezet wordt.


Met vriendelijke groet,


Felix Parnemann


________________________________
Van: Robin Bolscher <notifications@github.com>
Verzonden: maandag 20 februari 2017 16:51
Aan: athombv/am.smarter
CC: jklflipper; Author
Onderwerp: Re: [athombv/am.smarter] Doesn't work anymore? (#7)


Hi, I think something went wrong with your screenshots, I can't see them, could you hover over the red triangle with your mouse, this will show the error message which I need to find the problem.

**Comment by RobinBol** [comment]
Hi Felix,

I think your screenshots do not work as you are replying via email, try the github page of this issue (https://github.com/athombv/am.smarter/issues/7). But I get your problems, we are aware of some issues in the Smarter app, however as it is used by very few people it is not high on our priority list. I hope you understand this, I will try to make some time for it but do not expect it soon.

**Comment by RobinBol** [comment]
This should be fixed in the beta version of the Smarter app, could you test it and let me know if this resolves your issue?

**Comment by saro1975** [comment]
In my case homey does not see the smarter coffee at all, Am i doing somerhing wrong?

**Comment by RobinBol** [comment]
I will close this issue since the user who opened it is not responding anymore. @saro1975 it might be you have the smarter coffee v2 which is currently not supported by the app.
