### ISSUE TITLE
When come the mobile cards?

### ISSUE THREAD

**Issue by Jovink** [athombv/am.smarter#9]
Nou dat dus.

**Comment by RobinBol** [comment]
This should be fixed in the beta version of the Smarter app, could you test it and let me know if this resolves your issue?

**Comment by Jovink** [comment]
Yes in the old app it works. 
In the new one not yet.

**Comment by RobinBol** [comment]
You mean smartphone app? What does not work?

**Comment by Jovink** [comment]
Yes on the mobile app.
In the old app it is posible to select the amount off cups and start with brew.
In the new app it is not possible to start brewing. 
And on the ikettle ver2 it is also not possible to start heating. Or i don’t know how.

**Comment by RobinBol** [comment]
I have reported this to our smartphone app developers, therefore this will be resolved in a future update of the smartphone app! Thanks for reporting!
